name: swastha
description: A Health App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  flutter_bloc: ^8.0.1
  firebase_storage: ^10.2.14
  cloud_firestore: ^3.1.13
  image_picker: ^0.8.5
  image_cropper: ^2.0.0
  equatable: ^2.0.3
  flutter_zoom_drawer: ^3.0.2
  syncfusion_flutter_gauges: ^20.1.55
  flutter_advanced_drawer: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_spinkit: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/